name: github pages

on:
  push:
    branches:
      - main

concurrency:
  group: pages
  # cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - run: pnpm i
      - run: pnpm run build
      - run: cd example && pnpm run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: example/dist
          force_orphan: true
